base_url = "https://smacdo.com"
title = "smacdo.com"
description = "Scott MacDonald — systems programmer and game developer"
compile_sass = false
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown.highlighting]
enabled = true
theme = "ayu-dark"

[extra]
author = "Scott MacDonald"
