name: Reusable Deploy Workflow
on:
  workflow_call:
    inputs:
      deployment_name:
        required: true
        type: string
    secrets:
      DEPLOY_DIR:
        required: true
      SSH_HOST:
        required: true
      SSH_KEY:
        required: true
      SSH_USER:
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Test project
        run: npm test

      - name: Upload build artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: deployment-files
          path: ./dist

  deploy:
    name: Deploy to ${{ inputs.deployment_name }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Generate SSH keys
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >> ~/.ssh/config <<END
          Host remote-host
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
      - name: Get deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-files
          path: ./dist
      - name: Deploy
        run: |
          rsync --recursive --verbose --archive --compress --delay-updates --delete-after \
             ./dist/ ${{ secrets.SSH_USER }}@remote-host:/${{ secrets.DEPLOY_DIR }}/