name: Deploy to Production

on:
  push:
    tags:
      - 'releases-v\d+'

  workflow_dispatch:

jobs:
  call-deploy-template:
    uses: ./.github/workflows/deploy_template.yml
    with:
      deployment_name: smacdo.com
    environment: production
    secrets:
      DEPLOY_DIR: ${{ secrets.PROD_DEPLOY_DIR }}
      SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
      SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
      SSH_USER: ${{ secrets.PROD_SSH_USER }}