name: Deploy to Production

on:
  push:
    tags:
      - 'releases-v\d+'

  workflow_dispatch:

jobs:
  call-deploy-template:
    uses: ./.github/workflows/deploy_template.yml
    with:
      ssh_host: ${{ secrets.PROD_SSH_HOST }}
      ssh_key: ${{ secrets.PROD_SSH_KEY }}
      ssh_user: ${{ secrets.PROD_SSH_USER }}
      deploy_path: /home/${{ secrets.PROD_SSH_USER }}/smacdo.com/
    secrets:
      SSH_HOST_SECRET: ${{ secrets.PROD_SSH_HOST }}
      SSH_KEY_SECRET: ${{ secrets.PROD_SSH_KEY }}
      SSH_USER_SECRET: ${{ secrets.PROD_SSH_USER }}