name: Deploy to Staging

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  call-deploy-template:
    uses: ./.github/workflows/deploy_template.yml
    with:
      deploy_dir: staging.smacdo.com
    secrets:
      SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
      SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
      SSH_USER: ${{ secrets.STAGING_SSH_USER }}